name: xwidgets
channels:
- conda-forge
dependencies:
  # Build dependencies
- cmake
- cxx-compiler
- ninja
  # Host dependencies
- xeus>=3.2.0,<4
- cppzmq
- xproperty=0.11.0
- nlohmann_json
  # Test dependencies
- doctest >= 2.4.6
- json_schema_validator
- pre-commit
- cmake-format
